### ISSUE TITLE
feat: Add AWS lambda support for IPV6 outbound connections in VPC

### ISSUE THREAD

**Issue by Martijn02** [oss-serverless/serverless#15]
Any chance we can add support for Lambda to use a IPv6 for outgoing connections? Using IPv6 for outbound communication is a wonderful solution for lambda's that also need to connect to some internal services (elasticache and/or rds). It saves you a very expensive NAT gateway or transitlink endpoint for every environment you use this in.

Reference: https://aws.amazon.com/about-aws/whats-new/2023/10/aws-lambda-ipv6-outbound-connections-vpc

@rvaralda made a [pull request for this in the original serverless](https://github.com/serverless/serverless/pull/12243) repository, but his work was never merged. 

Since Serverless (v3) is now in maintenance mode, I was wondering if you would be open to incorporating this change into this project. This would be incredibly valuable for users who are looking to optimize their networking costs.

Note that this change only adds an optional key to the VPC config, and is fully backwards compatible with the serverless yaml spec.

Please let me know if there's anything I can help with to move this forward—I'd be happy to contribute or assist with testing!

**Comment by j0k3r** [comment]
I'm not a maintainer here, but as the fix looks small and is just about adding a new key in the config, it could be a good idea 👍🏼

**Comment by mnapoli** [comment]
Yes, a pull request would be welcome. I'm closing this to keep only bug reports 👍
