### ISSUE TITLE
Re-enable Serverless Components

### ISSUE THREAD

**Issue by serverlesspolska** [oss-serverless/serverless#9]
Hi @mnapoli,

Great work with this fork. I guess it was inevitable :-)

> Serverless Components support have been removed: these are old and unmaintained projects, it's very unlikely you are using them. That improves the boot time of the CLI.

Any chance to get it back?

I found that **Serverless Components** is an easy way to manage applications with several microservices.

Also, it can be used to deploy simultaneously to multiple regions. For example I used to work with a system that had production in 4 regions. Components allowed me to deploy serverless services to all those regions via a single `sls deploy ...`

**Comment by mnapoli** [comment]
Hi @serverlesspolska, unfortunately that's not planned.

You can use Serverless Components directly though, just install it and use its CLI. You don't need to have it in this project.
